version: '3.9'

services:
  prometheus:
    image: bitnami/prometheus:2
    container_name: core-prometheus
    volumes:
      - type: volume
        source: prometheus-data
        target: /opt/bitnami/prometheus/data
    expose:
      - 9090

  rabbitmq:
    image: rabbitmq:3-management
    container_name: core-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - type: volume
        source: rabbit-data
        target: /var/lib/rabbitmq/mnesia/
    expose:
      - 5672
      - 15672
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 15672

volumes:
  rabbit-data:
  prometheus-data:
  db-data: