services:
  #  postgres:
  #    image: postgres:10
  #    command: postgres -c 'max_connections=300'
  #    container_name: core-postgres
  #    restart: always
  #    environment:
  #      POSTGRES_DB: dataflow
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: rootpw
  #    expose:
  #      - 5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: core-rabbitmq
    #    volumes:
    #      - ./core/rabbitmq:/etc/rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - target: 15672
        published: 15672

#volumes:
#  db-data:
#
#secrets:
#  db-password:
#    file: db/password.txt

